name: Build latex files
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull_request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout commit
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v3
      - name: Find changed files
        run: |
          FILES=$(git --no-pager diff --name-only HEAD HEAD~1 | grep "^.*\.tex$")
          echo "FILES<<EOF" >> $GITHUB_ENV
          echo "$FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Build pdfs
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.FILES }}
      - name: Publish pdfs
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: "*.pdf"
      - name: "Enable lfs"
        if: false
        run: |
           git lfs track "*.pdf"
           git add .gitattributes
      - name: "Debug print git status"
        run: "git status"
      - name: Commit new pdfs
        uses: EndBug/add-and-commit@v9
        with:
          add: "*.pdf"
          committer_name: Pdf builder
          committer_email: noemail@example.com
          default_author: user_info
          message: '[no ci] Add pdfs'
          pathspec_error_handling: exitImmediately
          push: true
